name: John Doe Application
run-name: Build Project for ${{ github.repository_owner }} as actor ${{ github.actor }} 🚀
on: [push]

env:
  GITHUB_USER: ${{ github.repository_owner }}
  BACKEND_IMAGE_NAME: "ghcr.io/${{ github.repository_owner }}/backend:latest"
  FRONTEND_IMAGE_NAME: "ghcr.io/${{ github.repository_owner }}/backend:latest"

jobs:
  build-docker-images:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    steps:
      - run: echo "triggered by a ${{ github.event_name }} on ${{ runner.os }} repo ${{ github.repository }} branch ${{ github.ref }} ."
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          cache: maven

      - name: build backend
        run: |
          ./build.sh
        working-directory: backend

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend/www/package.json

      - name: build frontend
        run: |
          ./build.sh
        working-directory: frontend
      
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
       
      - name: push docker images
        run: |
          echo "tag backend $BACKEND_IMAGE_NAME and frontend $FRONTEND_IMAGE_NAME"
          docker tag backend $BACKEND_IMAGE_NAME
          docker push $BACKEND_IMAGE_NAME
          docker tag frontend $FRONTEND_IMAGE_NAME
          docker push $FRONTEND_IMAGE_NAME
    