name: John Doe Application
run-name: ${{ github.actor }} Build Project 🚀
on: [push]

env:
  GITHUB_USER: ${{ github.actor }}
  IMAGE_NAME: "ghcr.io/${{ github.actor }}/backend:latest"

jobs:
  build-docker-images:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "triggered by a ${{ github.event_name }} on ${{ runner.os }} repo ${{ github.repository }} branch ${{ github.ref }} ."
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          cache: maven

      - name: build backend
        run: |
          ./build.sh
        working-directory: backend

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend/www/package.json

      - name: build frontend
        run: |
          ./build.sh
        working-directory: frontend
    
    